version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    command: --max_allowed_packet=32505856
    networks:
      - frontend
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=simple
      - MYSQL_DATABASE=adult_dataset

  backend:
    image: "dineshsonachalam/gender-diversity-backend:latest"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - frontend
    ports:
      - "8002:8002"
    depends_on:
      - mysql
      
networks:
  frontend: