// Step 1: Create Action Types
export const UPDATE_GENDER_STATS = "UPDATE_GENDER_STATS";
export const UPDATE_RELATIONSHIP_STATS = "UPDATE_RELATIONSHIP_STATS";
export const UPDATE_ADULT_STATS = "UPDATE_ADULT_STATS";


