name: Docker

on:
  push:
    branches:
      - master
    tags:
      - latest

jobs:
  integration-tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Start the Postgres container
          run: |
            echo "127.0.0.1 postgres" | sudo tee -a /etc/hosts
            docker run \
            -d -p 5432:5432 \
            -e "POSTGRES_USER=dinesh" \
            -e "POSTGRES_PASSWORD=simple" \
            -e "POSTGRES_DB=dinesh-micro-apps" \
            -v $(pwd)/data:/var/lib/postgresql/data:z \
            postgres:9.6.21 
            echo $(pwd)
            ls
            sleep 15
            docker ps

        - name: Install backend and frontend dependencies
          run: |
            pip3 install -r backend/requirements.txt
            npm i --prefix frontend
        
        - name: Start backend and frontend applications in the background
          run: |
            cd backend
            python3 main.py &
            cd ..
            sleep 25

        - name: API testing
          run: |
            npm run start --prefix frontend &
            pytest backend -s

        - name: Cypress End to End testing
          run: |
            cd frontend
            sudo npm install -g --unsafe-perm=true --allow-root cypress
            sudo cypress run --headless --browser chrome

  upload-docker-image:
    needs: integration-tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Build backend and frontend image
        run: |
          npm i --prefix frontend
          npm run build --prefix frontend
          docker build --no-cache -t dineshsonachalam/gender-berkeley-backend:latest -f backend.Dockerfile .
          docker build --no-cache -t dineshsonachalam/gender-berkeley-frontend:latest -f frontend.Dockerfile .

      - name: Log into registry
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: |
          docker push dineshsonachalam/gender-berkeley-backend:latest
          docker push dineshsonachalam/gender-berkeley-frontend:latest
          
  deploy-to-k8-cluster:
    needs: upload-docker-image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: danielr1996/kubectl-action@1.0.0
      name: Backend deployment rolling restart to fetch recently build docker image from docker hub.
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
        args: rollout restart deployment uc-backend -n=dinesh
    
    - uses: danielr1996/kubectl-action@1.0.0
      name: Verify deployment for backend app
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
        args: rollout status deployment/uc-backend -n=dinesh

    - uses: danielr1996/kubectl-action@1.0.0
      name: Frontend deployment rolling restart to fetch recently build docker image from docker hub.
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
        args: rollout restart deployment uc-frontend -n=dinesh
    
    - uses: danielr1996/kubectl-action@1.0.0
      name: Verify deployment for frontend app
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
        args: rollout status deployment/uc-frontend -n=dinesh